### ISSUE TITLE
Aderyn VSCode needs Char Offset, not Byte Offset

### ISSUE THREAD

**Issue by TilakMaddy** [Cyfrin/aderyn-vscode#25]
![image](https://github.com/Cyfrin/aderyn-vscode/assets/11134428/8c30f477-905b-4f70-b24d-71664e4a8392)

Although the line numbers are correctly identified in the tree view, the underlined lines are different

**Comment by alexroan** [comment]
This is to do with ASCII characters at the beginning of the contracts.

The problems is with cloc. It appears in the ETH deposit contract also. Can you pleas open an issue on the core repo @TilakMaddy ?

**Comment by TilakMaddy** [comment]
Hmm.. Not sure I understood you correctly. 

1. Aren't we skipping cloc in vscode extension (`--skip-cloc`) 
2. If not, how are the nsloc helping in highlighting line numbers of issues?
3. I remember adding this line https://github.com/Cyfrin/aderyn/blob/96b423789ef36ae970d6ba975165a5daa2fcef5c/tests/contract-playground/src/cloc/AnotherHeavilyCommentedContract.sol#L39 with the sole purpose of making sure it doesn't break on non ascii characters (

**Comment by TilakMaddy** [comment]
@alexroan I want to make this 1 thing clear - In the tree view, it identifies the line correctly, but when I click on it, it highlights a different line. So I am unable to understand how this is a problem with the CLI tool. It must be with the VSCode right??

**Comment by TilakMaddy** [comment]
Let me see if I can fix it here : ) I'm sure somewhere in the javascript we are not treating source location offset and number of offset characters, but offset number of bytes instead. (Which in UTF-8 encoding, only for an ascii character, 1 byte is enough to represent 1 character)

**Comment by TilakMaddy** [comment]
Look the docs says  "character position", not byte offset
![image](https://github.com/Cyfrin/aderyn-vscode/assets/11134428/83573b45-99d8-45a0-9097-157af785ec02)

**Comment by TilakMaddy** [comment]
@alexroan With the PR #566 we have a new property `src_char` which gives offsets and length in terms of character rather than bytes. This should fix the problem : )

**Comment by alexroan** [comment]
Fixed by #39
