### ISSUE TITLE
Add Cyfrin x Aderyn VS Code Extension Logo

### ISSUE THREAD

**Issue by AnaArsonist** [Cyfrin/aderyn-vscode#34]
For the extension :)

![aderyn-vscode-logo](https://github.com/Cyfrin/aderyn-vscode/assets/113212503/c7dfd814-33fd-431c-ab22-3bb8fc79eecc)

**Comment by alexroan** [comment]
This SVG is for the sidebar icon 👍

**Comment by Eversmile12** [comment]
Version without separation lines (try both, see if the one above shows weird on VScode):
![VS Code Extension SVG](https://github.com/Cyfrin/aderyn-vscode/assets/72762629/c90abe0e-f61b-477c-8c2c-5bd6e57507e4)
